import Editor from '@monaco-editor/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef, useState } from 'react'
import styles from '../styles/Home.module.css'
import monaco from 'monaco-editor'

const Home: NextPage = () => {
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null)
  const [stdout, setStdout] = useState("")
  const [stderr, setStderr] = useState("")

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.header}>
        <button className={styles.button} onClick={async () => {
          if (editorRef.current !== null) {
            const source = editorRef.current.getValue();
            const body = {
              source: source,
            };
            const response = await fetch("http://localhost:8080/compile", {
              method: "POST",
              mode: "cors",
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(body),
            });
            const responseObj = await response.json();
            setStdout(responseObj.stdout);
            setStderr(responseObj.stderr);
          }
        }}>Run</button>
      </div>

      <div className={styles.editor}>
        <Editor
          width="50%"
          height="100%"
          defaultLanguage=""
          defaultValue="// some comment"
          theme="vs-dark"
          options={{
            fontSize: 16,
          }}
          // declaring second argument makes Next unhappy. why?
          onMount={(editor) => { editorRef.current = editor }}
        />
        <div id="stdout">
          {stdout}
          {stderr}
        </div>
      </div>
    </div>
  )
}

export default Home
