name: CI

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          # For running nixosTest
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - uses: cachix/cachix-action@v10
        with:
          name: satysfi-playground
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # - run: nix flake check
      - run: nix build .#packages.x86_64-linux.server
